### ISSUE TITLE
Writing to the Database

### ISSUE THREAD

**Issue by dmytri** [dmytri/terminusdb-todoapp#1]
https://dmytri.dev/terminusdb-todoapp/#/README?id=writing-to-the-database 

 Description

**Comment by dmytri** [comment]
Let me know if this makes sense.

**Comment by EmmanuelOga** [comment]
Looks great Dmytri, learning a lot from this! Also found some cool tangential stuff I did not know about like https://gitalk.github.io/ :-)

**Comment by EmmanuelOga** [comment]
If I get it right, each time you call DB.query with an update, that creates a new commit in TDB?

wdyt about queueing the commands? I mean, maybe the whole thing could work "offline" and have a "sync" that saves the progress if the user wants to. I know this is a demo but just double checking my understanding of the whole thing :-)

**Comment by dmytri** [comment]
Hey EmmanualOga, didn't notice this, let me know if you still have questions here.
